#!/usr/bin/env sh
set -eu

RANGE="${1:-}"

if [ -z "$RANGE" ]; then
  if git rev-parse --verify origin/main >/dev/null 2>&1; then
    RANGE="origin/main..HEAD"
  else
    RANGE="HEAD"
  fi
fi

PATTERN='^(Co-authored-by:[[:space:]]*(Claude|ChatGPT)|Generated with Claude Code|Generated by[[:space:]].+)'

TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

if ! git log --format='%H' "$RANGE" >/dev/null 2>&1; then
  echo "[attribution-check] Invalid commit range: $RANGE" >&2
  exit 2
fi

FOUND=0
for c in $(git log --format='%H' "$RANGE"); do
  git show -s --format=%B "$c" | nl -ba | sed "s/^/$c\t/" >> "$TMPFILE"
done

if grep -E "$PATTERN" "$TMPFILE" >/dev/null 2>&1; then
  FOUND=1
fi

if [ "$FOUND" -eq 1 ]; then
  echo "[attribution-check] Failed: banned attribution lines found in commit messages."
  echo
  echo "Matches:"
  grep -En "$PATTERN" "$TMPFILE" | sed 's/^/  /'
  echo
  echo "Fix instructions:"
  echo "1) If only the latest commit is affected:"
  echo "   git commit --amend"
  echo
  echo "2) If older commits are affected:"
  echo "   git rebase -i <base-commit-before-bad-commits>"
  echo
  echo "3) If history was already pushed, update remote safely:"
  echo "   git push --force-with-lease"
  echo
  echo "See docs/AI-COMMIT-CLEANUP.md for full safe rewrite steps."
  exit 1
fi

echo "[attribution-check] OK: no banned attribution lines found in $RANGE"
